public: false
type: "docs"
tags:
  - "collections management"
  - "policy"
  - "cellulose nitrate film"
  - "audiovisual"
title: "Cellulose Nitrate Still Picture and Motion Picture Film Policy"
description: "Policy for the storage of all cellulose nitrate film."
pages:
  - ["Cellulose Nitrate Still Picture and Motion Picture Film Policy", "index"]
