public: true
type: "docs"
category: "collection development and management"
tags:
  - "policy"
title: "Cellulose Nitrate Still Picture and Motion Picture Film Policy"
description: "Policy for the storage of all cellulose nitrate film."
pages:
  - ["Cellulose Nitrate Still Picture and Motion Picture Film Policy", "index"]
