public: true
type: "docs"
tags:
  - "collections management"
  - "policy"
  - "cellulose nitrate film"
  - "audiovisual"
title: "Cellulose Nitrate Still Picture and Motion Picture Film Policy"
description: "The policy for the storage of all cellulose nitrate still picture and motion picture film."
pages:
  - ["Cellulose Nitrate Still Picture and Motion Picture Film Policy", "index"]
